pipeline:
#  py35:
#    when:
#      event: [ pull_request ]
#      branch: [ master ]
#
#    image: plugins/docker
#    secrets: [docker_username, docker_password]
#    repo: tataucloud/python-horovod-mpich
#    registry: docker.io
#    dockerfile: Dockerfile
#    tags:
#      - '3.5'
#    build_args:
#      - PYTHON_VERSION=3.5


  py36:
    when:
      event: [ pull_request ]
      branch: [ master ]

    image: plugins/docker
    secrets: [docker_username, docker_password]
    repo: tataucloud/python-horovod-mpich
    registry: docker.io
    dockerfile: Dockerfile
    tags:
      - '3.6'
    build_args:
      - PYTHON_VERSION=3.6

# Not supported by TF yet
#  py37:
#    when:
#      branch: [master]
#    image: plugins/docker
#    secrets: [docker_username, docker_password]
#    repo: tataucloud/python-horovod-mpich
#    registry: docker.io
#    dockerfile: Dockerfile
#    tags:
#      - '3.7'
#    build_args:
#      - PYTHON_VERSION=3.7

  notify:
    image: plugins/slack
    secrets: [slack_webhook]
    webhook: $SLACK_WEBHOOK
    channel: "build-status"
    username: drone
    template: >
      {{#success build.status}}
        author: {{build.author}}
        repo: {{repo.name}}/{{build.branch}}
        link: {{build.link}}
        build {{build.number}} `{{build.status}}`. Good job {{build.author}}!
      {{else}}
        author: {{build.author}}
        repo: {{repo.name}}/{{build.branch}}
        link: {{build.link}}
        build {{build.number}} `{{build.status}}`. Fix me please. <@build-status>
      {{/success}}

    when:
      event: [ pull_request ]
      branch: [ master ]
      status: [ success, failure ]